# Generated by Django 3.1.2 on 2022-06-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20220623_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eprice', models.PositiveBigIntegerField()),
                ('mprice', models.PositiveBigIntegerField()),
            ],
        ),
    ]
