# Generated by Django 3.1.2 on 2022-06-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_fuel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fuel',
        ),
    ]
