# Generated by Django 3.1.2 on 2022-06-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20220624_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(max_length=200)),
                ('Purchase', models.FloatField()),
                ('sales', models.FloatField()),
                ('expense', models.FloatField()),
                ('netprofit', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='eprice',
            new_name='elitres',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='expense',
            new_name='mlitres',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='mrice',
            new_name='volatility',
        ),
    ]
