# Generated by Django 3.1.2 on 2022-06-24 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20220624_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculation',
            old_name='Purchase',
            new_name='purchase',
        ),
    ]
