# Generated by Django 3.1.2 on 2022-06-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20220624_1332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculation',
        ),
    ]
